// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using Xenko.Graphics;
using Xenko.Rendering;

namespace NEWorld.Effects
{
    public static partial class VertexTextureTerrainKeys
    {
        public static readonly ValueParameterKey<float> TexturePerLine = ParameterKeys.NewValue<float>();
        public static readonly ObjectParameterKey<SamplerState> MeshTextureSampler = ParameterKeys.NewObject<SamplerState>();
        public static readonly ObjectParameterKey<Texture> Almg = ParameterKeys.NewObject<Texture>();
    }
}
